export const RESET="RESET"
export const ERROR = "ERROR";
export const LOADING = "LOADING";
export const GET_USERS = "GET_USERS";
export const SINGLE_USERS = "SINGLE_USERS";
export const UPDATE_USERS = "UPDATE_USERS";
export const CREATE_USERS = "CREATE_USERS";
export const DELETED_USERS = "DELETED_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const UPDATE_USERS_SUCCESS = "UPDATE_USERS_SUCCESS"
export const CREATE_USERS_SUCCESS = "CREATE_USERS_SUCCESS";
export const SINGLE_USERS_SUCCESS = "SINGLE_USERS_SUCCESS";
export const DELETED_USERS_SUCCESS = "DELETED_USERS_SUCCESS";

